### ISSUE TITLE
Failed to extract mingw-x64 exit status 2

### ISSUE THREAD

**Issue by johnjohnsp1** [moloch--/denim#6]
Hi,
i'm following the procedure to install denim but once issued denim setup i get this error:

C:\temp\denim>denim setup
[1m[36m[*] [0mDownloading 7-zip ...
375.83 KiB / 375.83 KiB [----------------------------------------------------------------------------] 100.00% ? p/s 0s
[1m[36m[*] [0mExtracting 7z ...
[2K[1m[36m[*] [0mDownloading mingw-x64 ...
47.08 MiB / 47.08 MiB [------------------------------------------------------------------] 100.00% 533.66 KiB p/s 1m31s
[1m[36m[*] [0mExtracting mingw-x64 ...
[1m[31m[!] [0mFailed to extract mingw-x64 exit status 2

C:\temp\denim>7z

7-Zip 21.05 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-11-20

Usage: 7z <command> [<switches>...] <archive_name> [<file_names>...] [@listfile]

<Commands>
  a : Add files to archive
  b : Benchmark
  d : Delete files from archive
  e : Extract files from archive (without using directory names)
  h : Calculate hash values for files
  i : Show information about supported formats
  l : List contents of archive

i'm doing something wrong or miss something ?
7z is working ... keep stopping at mingw-x64 step..

thanks

**Comment by 4s0ck3t** [comment]
I also had this issue, it was to do with my VPN and mingw download not finishing correctly

**Comment by moloch--** [comment]
Yea i think the timeout is set incorrectly on the download, if it doesnt finish in 10m it fails.

**Comment by ghost** [comment]
wondering if this had been fixed in a commit. Thank you!

**Comment by moloch--** [comment]
Nope sorry not had anytime to work on this project in a while, happy to accepts PRs though!

**Comment by ghost** [comment]
Found the issue, if someone already has .denim in User Folder, with mingw-x64 folder, this throws an error. @moloch--

**Comment by nzyuko** [comment]
Anyone found a fix? I have tried removing the .denim in user folder still doesnt fix the issue. I am not using VPN. It fails after 5 seconds

**Comment by SantaLaMuerte** [comment]
>  .denim in User Folder > delete 
and now all perfect , thanks for advice @stevesec
